from test__sqlLiteMovieRepository import SqlLiteMovieRepositoryTest
from test__tntvillageWebpage import TntvillageWebpageTest
from test__corsaroneroWebpage import CorsaroneroWebpageTest
from test__urlLibHtmlRetriever import UrlLibHtmlRetrieverTest
